Vagrant.configure("2") do |config|
  config.ssh.username = "vagrant"
  config.ssh.insert_key = true
  config.vm.synced_folder ".", "/vagrant", disabled: true
  config.vm.network "private_network", type: "dhcp", auto_config: false

  config.vm.provider "vmware_desktop" do |vmware|
    vmware.allowlist_verified = true
  end
end
